amino_acid_dict = {
    "A": ["Alanine", "Ala"],
    "R": ["Arginine", "Arg"],
    "N": ["Asparagine", "Asn"],
    "D": ["Aspartic acid", "Asp"],
    "C": ["Cysteine", "Cys"],
    "E": ["Glutamic acid", "Glu"],
    "Q": ["Glutamine", "Gln"],
    "G": ["Glycine", "Gly"],
    "H": ["Histidine", "His"],
    "I": ["Isoleucine", "Ile"],
    "L": ["Leucine", "Leu"],
    "K": ["Lysine", "Lys"],
    "M": ["Methionine", "Met"],
    "F": ["Phenylalanine", "Phe"],
    "P": ["Proline", "Pro"],
    "S": ["Serine", "Ser"],
    "T": ["Threonine", "Thr"],
    "W": ["Tryptophan", "Trp"],
    "Y": ["Tyrosine", "Tyr"],
    "V": ["Valine", "Val"]
}
